### ISSUE TITLE
Nothing displaying!

### ISSUE THREAD

**Issue by lexterror** [sdepold/vanilla-rss#31]
Is it currently working?

Thank you!

**Comment by Ry3yr** [comment]
It is.
But only on certain webhosts.
Githubpages, codeberg and bitbucket all fail.

Only http://alceawisteria.byethost7.com/RSS/rss-ytfolk.html could run it.

Almot asif some serverside execution was going on
(uncommon for javascript ...)

**Comment by sdepold** [comment]
Should work just fine. Please let me know more details and reopen this ticket.
